"""
Export adapters — compile a HarnessSpec into the native plugin/agent format of
a host coding agent, so harnesses built here run INSIDE those tools:

  claude-code : real plugin (.claude-plugin/plugin.json + agents/ + skills/ +
                commands/). Agents become native subagents; the host's own
                orchestration (Task tool) replaces our orchestrator.
  codex       : AGENTS.md team charter + prompts/<agent>.md. Codex has no
                native subagents, so the charter instructs the single agent to
                role-play the team stages in order.
  opencode    : .opencode/agent/*.md (subagent markdown, Claude-Code-like
                frontmatter) + command/run-<name>.md.

What ports: team structure, roles, system prompts, skills, pattern wiring.
What doesn't: our memory stores, guardrail budgets, and goal loop — hosts have
their own equivalents (noted in the generated README of each export).
"""

from __future__ import annotations

import json
from pathlib import Path

# our tool names -> Claude Code tool names
CLAUDE_TOOLS = {"read_file": "Read", "write_file": "Write", "list_files": "Glob",
                "run_shell": "Bash", "web_search": "WebSearch", "fetch_url": "WebFetch"}

PATTERN_NOTES = {
    "pipeline": "Run agents strictly in this order, passing each stage's output to the next",
    "fanout": "Run all agents except the last in parallel on the same task, then have the last agent merge their outputs",
    "expert_pool": "Pick the 1-3 most relevant agents for the task and run only those",
    "producer_reviewer": "Alternate: first agent drafts, second critiques; repeat until the reviewer replies APPROVED (max 3 rounds)",
    "supervisor": "The supervisor agent coordinates: it delegates subtasks to the other agents and integrates results",
    "hierarchical": "The supervisor delegates; delegates may further break down their subtasks before answering",
}


def _slug(name: str) -> str:
    return name.replace("_", "-")


def _flow_text(spec) -> str:
    order = spec.flow or [a.name for a in spec.agents]
    flat = [x for i in order for x in (i if isinstance(i, list) else [i])]
    return " -> ".join(flat)


# ─────────────────────────────────────────────────────────── claude code
def export_claude_code(spec, harness_dir: Path, out: Path) -> Path:
    plugin = out / f"{_slug(spec.name)}-plugin"
    (plugin / ".claude-plugin").mkdir(parents=True, exist_ok=True)
    (plugin / ".claude-plugin" / "plugin.json").write_text(json.dumps({
        "name": _slug(spec.name),
        "description": spec.description,
        "version": "0.1.0",
    }, indent=2))

    # agents -> native subagents
    agents_dir = plugin / "agents"
    agents_dir.mkdir(exist_ok=True)
    for a in spec.agents:
        tools = ", ".join(sorted({CLAUDE_TOOLS[t] for t in a.tools if t in CLAUDE_TOOLS}))
        model = "haiku" if "haiku" in a.model else "sonnet"
        body = a.system_prompt
        if a.skills:
            body += ("\n\nBefore starting, read your skill(s) with the Skill tool: "
                     + ", ".join(_slug(s) for s in a.skills))
        (agents_dir / f"{_slug(a.name)}.md").write_text(
            f"---\nname: {_slug(a.name)}\ndescription: {a.role}. Use this agent "
            f"for that part of {spec.name} work.\n"
            + (f"tools: {tools}\n" if tools else "")
            + f"model: {model}\n---\n\n{body}\n")

    # skills -> native skills
    for skill_file in (harness_dir / "skills").glob("*.md"):
        sdir = plugin / "skills" / _slug(skill_file.stem)
        sdir.mkdir(parents=True, exist_ok=True)
        (sdir / "SKILL.md").write_text(
            f"---\nname: {_slug(skill_file.stem)}\ndescription: Procedures and "
            f"heuristics for {spec.name} agents. Use when doing {spec.name} work."
            f"\n---\n\n{skill_file.read_text()}\n")

    # a /run command encoding the team pattern
    cmds = plugin / "commands"
    cmds.mkdir(exist_ok=True)
    roster = "\n".join(f"- {_slug(a.name)}: {a.role}" for a in spec.agents)
    (cmds / f"run-{_slug(spec.name)}.md").write_text(
        f"---\ndescription: Run the {spec.name} agent team on a task\n---\n\n"
        f"Run the {spec.name} team on this task: $ARGUMENTS\n\n"
        f"Team pattern: {spec.pattern} — {PATTERN_NOTES[spec.pattern]}.\n"
        f"Execution order/wiring: {_flow_text(spec)}\n\nTeam (launch each via "
        f"the Task tool with the matching subagent):\n{roster}\n\n"
        "Integrate all results into one final deliverable and verify it against "
        "these quality criteria before finishing:\n"
        + "\n".join(f"- {c}" for c in spec.eval.quality_criteria))

    (plugin / "README.md").write_text(
        f"# {_slug(spec.name)} (Claude Code plugin)\n\nGenerated by harness-builder.\n\n"
        f"Install (local): `claude --plugin-dir {plugin.resolve()}` or add to a "
        "plugin marketplace.\nThen: `/run-" + _slug(spec.name) + " <task>`\n\n"
        "Note: harness-builder's memory stores, token budgets, and goal loop "
        "don't port — Claude Code has its own memory, permissions, and hooks; "
        "configure those there.\n")
    return plugin


# ─────────────────────────────────────────────────────────────── codex
def export_codex(spec, harness_dir: Path, out: Path) -> Path:
    root = out / f"{_slug(spec.name)}-codex"
    prompts = root / "prompts"
    prompts.mkdir(parents=True, exist_ok=True)

    roster = []
    for a in spec.agents:
        skills = "\n\n".join((harness_dir / "skills" / f"{s}.md").read_text()
                             for s in a.skills
                             if (harness_dir / "skills" / f"{s}.md").exists())
        (prompts / f"{_slug(a.name)}.md").write_text(
            f"# Role: {a.name}\n\n{a.system_prompt}\n\n{skills}\n")
        roster.append(f"- **{a.name}** ({a.role}) — full brief in prompts/{_slug(a.name)}.md")

    (root / "AGENTS.md").write_text(
        f"# {spec.name} — team charter\n\n{spec.description}\n\n"
        "Codex has no native subagents, so when working in this repo you "
        "role-play a coordinated team. Adopt one role at a time, fully, using "
        "its brief file.\n\n## Team\n" + "\n".join(roster)
        + f"\n\n## Orchestration ({spec.pattern})\n{PATTERN_NOTES[spec.pattern]}.\n"
        f"Wiring: {_flow_text(spec)}\n\nBetween roles, write each stage's output "
        "to a file in ./work/ and have the next role read it — files are the "
        "message bus.\n\n## Definition of done\n"
        + "\n".join(f"- {c}" for c in spec.eval.quality_criteria)
        + "\n\nIterate (goal loop) until every criterion is met or you have "
          "clearly explained the blocker.\n")
    return root


# ───────────────────────────────────────────────────────────── opencode
def export_opencode(spec, harness_dir: Path, out: Path) -> Path:
    root = out / f"{_slug(spec.name)}-opencode"
    agent_dir = root / ".opencode" / "agent"
    cmd_dir = root / ".opencode" / "command"
    agent_dir.mkdir(parents=True, exist_ok=True)
    cmd_dir.mkdir(parents=True, exist_ok=True)

    for a in spec.agents:
        skills = "\n\n".join((harness_dir / "skills" / f"{s}.md").read_text()
                             for s in a.skills
                             if (harness_dir / "skills" / f"{s}.md").exists())
        (agent_dir / f"{_slug(a.name)}.md").write_text(
            f"---\ndescription: {a.role}\nmode: subagent\n---\n\n"
            f"{a.system_prompt}\n\n{skills}\n")

    roster = "\n".join(f"- @{_slug(a.name)}: {a.role}" for a in spec.agents)
    (cmd_dir / f"run-{_slug(spec.name)}.md").write_text(
        f"---\ndescription: Run the {spec.name} team on a task\n---\n\n"
        f"Run the {spec.name} team on: $ARGUMENTS\n\n"
        f"Pattern: {spec.pattern} — {PATTERN_NOTES[spec.pattern]}.\n"
        f"Wiring: {_flow_text(spec)}\n\nSubagents:\n{roster}\n\n"
        "Quality criteria for the final deliverable:\n"
        + "\n".join(f"- {c}" for c in spec.eval.quality_criteria))
    (root / "README.md").write_text(
        f"# {spec.name} (opencode export)\n\nDrop the .opencode/ directory into "
        "your project root, then use /run-" + _slug(spec.name) + " <task> or "
        "mention subagents with @name.\n")
    return root


EXPORTERS = {"claude-code": export_claude_code, "codex": export_codex,
             "opencode": export_opencode}


def export(spec, harness_dir: str | Path, target: str, out: str | Path = "exports") -> Path:
    if target not in EXPORTERS:
        raise ValueError(f"unknown target '{target}'. Choose: {', '.join(EXPORTERS)}")
    out_path = EXPORTERS[target](spec, Path(harness_dir), Path(out))
    return out_path
